---
deployment:
  tasks:
    - /bin/chmod -R 775 /home/shars/repositories/modulosim_multinegozio/storage
    - /bin/chmod -R 775 /home/shars/repositories/modulosim_multinegozio/bootstrap/cache
    - /bin/cp -R /home/shars/repositories/modulosim_multinegozio/public/. /home/shars/public_html/
    - /bin/cp /home/shars/repositories/modulosim_multinegozio/cpanel-public-index.php /home/shars/public_html/index.php
    - /usr/local/bin/php /home/shars/repositories/modulosim_multinegozio/artisan migrate --force --no-interaction
    - /usr/local/bin/php /home/shars/repositories/modulosim_multinegozio/artisan optimize:clear
    - /usr/local/bin/php /home/shars/repositories/modulosim_multinegozio/artisan storage:link --force
